stages:
  - build
  - test
  - deploy

make_nsgt:
  stage: build
  script:
    - . $HOME/.profile
    - make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*
    expire_in: 1h

test_nsgt:
  stage: test
  script:
    - . $HOME/.profile
    - export PATH="$PATH:~/bin:~/.cabal/bin:~/.local/bin"
    - make test

upload_nsgt:
  stage: deploy
  script:
    - . $HOME/.profile
    - export PATH="$PATH:~/bin:~/.cabal/bin:~/.local/bin"
    - make upload
