stages:
  - build
  - test
  - deploy

make_nsgt:
  stage: build
  script:
    - . $HOME/.profile
    - make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*
    expire_in: 1h

test_nsgt:
  stage: test
  script:
    - . $HOME/.profile
