make_nsgt:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*
    expire_in: 1h

test_nsgt:
  stage: test
  script:
    - make test

upload_pypi:
  stage: deploy
  script:
    - make upload_pypi

push_github:
  stage: deploy
  script:
    - make push_github
